spring.application.name=centroplus-api
spring.datasource.url=jdbc:h2:mem:centroplusdb;DATABASE_TO_UPPER=false
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.application.name=CentroPlus Connect API
spring.sql.init.encoding=UTF-8